// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MirthSystems.Pulse.Infrastructure.Data;
using NetTopologySuite.Geometries;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MirthSystems.Pulse.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250504202052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "day_of_week", new[] { "sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "special_types", new[] { "food", "drink", "entertainment" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "address_standardizer");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "address_standardizer_data_us");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "plpgsql");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_raster");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_sfcgal");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_tiger_geocoder");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis_topology");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MirthSystems.Pulse.Core.Models.Entities.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("The unique identifier for the address. This is the primary key for the address entity in the database.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country")
                        .HasComment("The country where the address is located. This required field helps determine address formatting and timezone derivation. Examples include: 'United States', 'Canada', 'United Kingdom', 'Australia'. Use the full country name rather than abbreviations or codes.");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locality")
                        .HasComment("The city, town, or locality where the address is located. Examples include: 'Springfield' (USA), 'Toronto' (Canada), 'Manchester' (UK).");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location")
                        .HasComment("The geographical coordinates (latitude and longitude) of the address. Used for mapping and location-based features. This uses NetTopologySuite.Geometries.Point to store geographic coordinates. Example: new Point(-87.6298, 41.8781) { SRID = 4326 } for Chicago.");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postcode")
                        .HasComment("The postal or ZIP code of the address's location. This required field supports various international formats. Examples include: '62701' (USA), 'M5V 2T6' (Canada), 'SW1A 1AA' (UK), '2000' (Australia).");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region")
                        .HasComment("The administrative region where the address is located. This required field can represent a state, province, territory, or other regional division depending on the country. Examples include: 'Illinois' (USA), 'Ontario' (Canada), 'Queensland' (Australia), 'Bavaria' (Germany).");

                    b.Property<string>("SecondaryAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("secondary_address")
                        .HasComment("This optional field captures additional address details like suite or unit numbers. Examples include: 'Suite 200' (USA), 'Flat 3' (UK), 'Apartment 12B' (General).");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("street_address")
                        .HasComment("This required field captures the primary address information, typically including the street number and name. Examples include: '123 Main St' (USA), '10 Downing Street' (UK), '35 Rue du Faubourg Saint-Honoré' (France).");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("MirthSystems.Pulse.Core.Models.Entities.OperatingSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("The unique identifier for the operating schedule entry. This is the primary key for the OperatingSchedule entity in the database.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week")
                        .HasComment("The day of the week for this operating schedule entry. This uses the standard .NET System.DayOfWeek enum. The values are: Sunday (0), Monday (1), Tuesday (2), etc.");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed")
                        .HasComment("A value indicating whether the venue is closed on this day. When true, the venue is completely closed on this day of the week. When false, the venue is open according to the TimeOfOpen and TimeOfClose properties.");

                    b.Property<LocalTime>("TimeOfClose")
                        .HasColumnType("time")
                        .HasColumnName("time_of_close")
                        .HasComment("The closing time for the venue on this day. Uses NodaTime's LocalTime to accurately represent time-of-day without date or timezone. If this is earlier than TimeOfOpen, it's interpreted as closing after midnight (the next day). This property is not relevant when IsClosed is true.");

                    b.Property<LocalTime>("TimeOfOpen")
                        .HasColumnType("time")
                        .HasColumnName("time_of_open")
                        .HasComment("The opening time for the venue on this day. Uses NodaTime's LocalTime to accurately represent time-of-day without date or timezone. This property is not relevant when IsClosed is true.");

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint")
                        .HasColumnName("venue_id")
                        .HasComment("The foreign key to the Venue entity. This represents the venue to which this operating schedule applies. This is a required field and is used to establish the relationship with the Venue entity.");

                    b.HasKey("Id")
                        .HasName("pk_operating_schedules");

                    b.HasIndex("VenueId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_operating_schedules_venue_id_day_of_week");

                    b.ToTable("operating_schedules", (string)null);
                });

            modelBuilder.Entity("MirthSystems.Pulse.Core.Models.Entities.Special", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("The unique identifier for the special. This is the primary key for the Special entity in the database.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content")
                        .HasComment("A brief description of the special. This required field provides details about what the special entails, making it clear to users what is being offered. Examples include: 'Half-Price Wings Happy Hour', 'Live Jazz Night', 'Buy One Get One Free Draft Beer'.");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("The timestamp when the special was created. Example: '2023-04-01T09:00:00Z' for a special created on April 1, 2023.");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_user_id")
                        .HasComment("The ID of the user who created the special. Example: 'auth0|12345' for the user who created the special.");

                    b.Property<string>("CronSchedule")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cron_schedule")
                        .HasComment("A CRON expression defining the recurrence schedule for the special, or null if not recurring. Common examples: Daily at 5 PM: '0 17 * * *', Every Monday at 8 PM: '0 20 * * 1', Weekdays at 4 PM: '0 16 * * 1-5'.");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("The timestamp when the special was deleted, if applicable. Example: '2023-05-01T12:00:00Z' for a special deleted on May 1, 2023.");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by_user_id")
                        .HasComment("The ID of the user who deleted the special, if applicable. Example: 'auth0|12345' for the user who performed the deletion.");

                    b.Property<LocalTime?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time")
                        .HasComment("The end time of the special on the same day, or null if it spans multiple days or has no daily end. This optional field is interpreted in the venue's timezone. Examples include: 10 PM concert end: LocalTime(22, 0), 7 PM happy hour end: LocalTime(19, 0), Multi-day special: null.");

                    b.Property<LocalDate?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date")
                        .HasComment("The expiration date of the special, or null if ongoing or same-day. For one-time specials, this is the end date if multi-day. For recurring specials, this is the last occurrence. Examples include: Multi-day sale: LocalDate(2023, 11, 3), Recurring end: LocalDate(2024, 3, 1), Same-day special: null.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Whether the special has been soft-deleted. Default is false. When true, the special is considered deleted but remains in the database for auditing purposes.");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring")
                        .HasComment("Determines whether the special repeats over time. If false, the special is a one-time event. If true, it recurs according to the CronSchedule. Examples include: One-time concert: false, Weekly happy hour: true.");

                    b.Property<LocalDate>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date")
                        .HasComment("The start date of the special. For one-time specials, this is the event date. For recurring specials, this is the first occurrence. The date is interpreted in the venue's timezone.");

                    b.Property<LocalTime>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time")
                        .HasComment("The start time of the special on the start date or each recurrence. This required field is interpreted in the venue's timezone. Examples include: 8 PM concert: LocalTime(20, 0), 5 PM happy hour: LocalTime(17, 0).");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type")
                        .HasComment("The category of the special, such as Food, Drink, or Entertainment. This required field helps classify and filter specials for users. Examples include: SpecialTypes.Food, SpecialTypes.Drink, SpecialTypes.Entertainment.");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("The timestamp when the special was last updated, if applicable. Example: '2023-04-15T14:00:00Z' for a special updated on April 15, 2023.");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by_user_id")
                        .HasComment("The ID of the user who last updated the special, if applicable. Example: 'auth0|12345' for the user who last updated the special.");

                    b.Property<long>("VenueId")
                        .HasColumnType("bigint")
                        .HasColumnName("venue_id")
                        .HasComment("The foreign key to the Venue entity. This represents the venue to which this special applies.");

                    b.HasKey("Id")
                        .HasName("pk_specials");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_specials_venue_id");

                    b.ToTable("specials", (string)null);
                });

            modelBuilder.Entity("MirthSystems.Pulse.Core.Models.Entities.Venue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("The unique identifier for the venue. This is the primary key for the venue entity in the database.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id")
                        .HasComment("The foreign key to the Address entity. This represents the physical address where the venue is located. This is a required field and is used to establish the relationship with the Address entity.");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("The timestamp when the venue was created. Example: '2023-01-01T08:00:00Z' for a venue created on January 1, 2023.");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_user_id")
                        .HasComment("The ID of the user who created the venue. Example: 'auth0|12345' for the user who created the venue.");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at")
                        .HasComment("The timestamp when the venue was deleted, if applicable. Example: '2023-03-01T12:00:00Z' for a venue deleted on March 1, 2023.");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deleted_by_user_id")
                        .HasComment("The ID of the user who deleted the venue, if applicable. Example: 'auth0|12345' for the user who performed the deletion.");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description")
                        .HasComment("This optional field provides an overview of the venue's offerings or unique features. Examples include: 'A cozy pub with live music and craft beers.', 'A classic diner serving daily specials and homestyle meals.'");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email")
                        .HasComment("This optional field allows for direct email contact with the venue. Examples include: 'info@rustyanchorpub.com', 'contact@downtownmusichall.com'.");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted")
                        .HasComment("Whether the venue has been soft-deleted. Default is false. When true, the venue is considered deleted but remains in the database for auditing purposes.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name")
                        .HasComment("This required field provides the primary identifier for the venue as displayed to users. Examples of venue names include: 'The Rusty Anchor Pub', 'Downtown Music Hall', 'Cafe Milano'.");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number")
                        .HasComment("This optional field allows users to contact the venue directly and supports international formats. Examples include: '+1 (555) 123-4567' (USA), '+44 20 7946 0958' (UK), '+61 2 9876 5432' (Australia).");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile_image")
                        .HasComment("URL to the venue's profile image (square format). Examples include: 'https://cdn.pulse.com/venues/123456/profile.jpg'. Recommended image specs: 512x512 pixels, square aspect ratio, JPG or PNG format.");

                    b.Property<Instant?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("The timestamp when the venue was last updated, if applicable. Example: '2023-02-15T10:00:00Z' for a venue updated on February 15, 2023.");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by_user_id")
                        .HasComment("The ID of the user who last updated the venue, if applicable. Example: 'auth0|12345' for the user who last updated the venue.");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website")
                        .HasComment("This optional field provides a link to the venue's online presence. Examples include: 'https://www.rustyanchorpub.com', 'https://downtownmusichall.com'. Always include the full URL including the protocol.");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasDatabaseName("ix_venues_address_id");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("MirthSystems.Pulse.Core.Models.Entities.OperatingSchedule", b =>
                {
                    b.HasOne("MirthSystems.Pulse.Core.Models.Entities.Venue", "Venue")
                        .WithMany("BusinessHours")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operating_schedules_venues_venue_id");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("MirthSystems.Pulse.Core.Models.Entities.Special", b =>
                {
                    b.HasOne("MirthSystems.Pulse.Core.Models.Entities.Venue", "Venue")
                        .WithMany("Specials")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_specials_venues_venue_id");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("MirthSystems.Pulse.Core.Models.Entities.Venue", b =>
                {
                    b.HasOne("MirthSystems.Pulse.Core.Models.Entities.Address", "Address")
                        .WithOne("Venue")
                        .HasForeignKey("MirthSystems.Pulse.Core.Models.Entities.Venue", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_venues_address_id");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("MirthSystems.Pulse.Core.Models.Entities.Address", b =>
                {
                    b.Navigation("Venue");
                });

            modelBuilder.Entity("MirthSystems.Pulse.Core.Models.Entities.Venue", b =>
                {
                    b.Navigation("BusinessHours");

                    b.Navigation("Specials");
                });
#pragma warning restore 612, 618
        }
    }
}
