// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pulse.Infrastructure;

#nullable disable

namespace Pulse.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250408225219_AddSocialAndLocationFeatures")]
    partial class AddSocialAndLocationFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "day_of_week", new[] { "sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "special_types", new[] { "food", "drink", "entertainment" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pulse.Core.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Point>("DefaultSearchLocation")
                        .HasColumnType("geography")
                        .HasColumnName("default_search_location");

                    b.Property<string>("DefaultSearchLocationString")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("default_search_location_string");

                    b.Property<double>("DefaultSearchRadius")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(5.0)
                        .HasColumnName("default_search_radius");

                    b.Property<Instant?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("OptedInToLocationServices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("opted_in_to_location_services");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("DefaultSearchLocation")
                        .HasDatabaseName("ix_users_default_search_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DefaultSearchLocation"), "GIST");

                    b.HasIndex("LastLoginAt")
                        .HasDatabaseName("ix_users_last_login_at");

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_provider_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.OperatingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_closed");

                    b.Property<LocalTime>("TimeOfClose")
                        .HasColumnType("time")
                        .HasColumnName("time_of_close");

                    b.Property<LocalTime>("TimeOfOpen")
                        .HasColumnType("time")
                        .HasColumnName("time_of_open");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_business_hours");

                    b.HasIndex("VenueId", "DayOfWeek")
                        .IsUnique()
                        .HasDatabaseName("ix_business_hours_venue_id_day_of_week");

                    b.ToTable("business_hours", (string)null);
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsExpired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_expired");

                    b.Property<string>("TextContent")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("text_content");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer")
                        .HasColumnName("venue_id");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("video_url");

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_posts_created_at");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_posts_expires_at");

                    b.HasIndex("IsExpired")
                        .HasDatabaseName("ix_posts_is_expired");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_posts_user_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_posts_venue_id");

                    b.HasIndex("VenueId", "ExpiresAt")
                        .HasDatabaseName("ix_posts_venue_id_expires_at");

                    b.HasIndex("VenueId", "IsExpired")
                        .HasDatabaseName("ix_posts_venue_id_is_expired");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.PostVibe", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("post_id");

                    b.Property<int>("VibeId")
                        .HasColumnType("integer")
                        .HasColumnName("vibe_id");

                    b.HasKey("PostId", "VibeId")
                        .HasName("pk_post_vibes");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_post_vibes_post_id");

                    b.HasIndex("VibeId")
                        .HasDatabaseName("ix_post_vibes_vibe_id");

                    b.ToTable("post_vibes", (string)null);
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Special", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content");

                    b.Property<LocalTime?>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<LocalDate?>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<string>("RecurringSchedule")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("recurring_schedule");

                    b.Property<LocalDate>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<LocalTime>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_specials");

                    b.HasIndex("ExpirationDate")
                        .HasDatabaseName("ix_specials_expiration_date");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_specials_start_date");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_specials_type");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_specials_venue_id");

                    b.HasIndex("StartDate", "StartTime")
                        .HasDatabaseName("ix_specials_start_date_start_time");

                    b.ToTable("specials", (string)null);
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.HasIndex("UsageCount")
                        .HasDatabaseName("ix_tags_usage_count");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.TagSpecial", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.Property<int>("SpecialId")
                        .HasColumnType("integer")
                        .HasColumnName("special_id");

                    b.HasKey("TagId", "SpecialId")
                        .HasName("pk_tag_specials");

                    b.HasIndex("SpecialId")
                        .HasDatabaseName("ix_tag_specials_special_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_tag_specials_tag_id");

                    b.ToTable("tag_specials", (string)null);
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address_line2");

                    b.Property<string>("AddressLine3")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address_line3");

                    b.Property<string>("AddressLine4")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address_line4");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ImageLink")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_link");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("locality");

                    b.Property<Point>("Location")
                        .HasColumnType("geography")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postcode");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<int>("VenueTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("venue_type_id");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_venues_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_venues_name");

                    b.HasIndex("VenueTypeId")
                        .HasDatabaseName("ix_venues_venue_type_id");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.VenueType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_venue_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_venue_types_name");

                    b.ToTable("venue_types", (string)null);
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Vibe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.HasKey("Id")
                        .HasName("pk_vibes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vibes_name");

                    b.HasIndex("UsageCount")
                        .HasDatabaseName("ix_vibes_usage_count");

                    b.ToTable("vibes", (string)null);
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.OperatingSchedule", b =>
                {
                    b.HasOne("Pulse.Core.Models.Entities.Venue", "Venue")
                        .WithMany("BusinessHours")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_hours_venues_venue_id");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Post", b =>
                {
                    b.HasOne("Pulse.Core.Models.Entities.ApplicationUser", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_users_user_id");

                    b.HasOne("Pulse.Core.Models.Entities.Venue", "Venue")
                        .WithMany("Posts")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_venues_venue_id");

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.PostVibe", b =>
                {
                    b.HasOne("Pulse.Core.Models.Entities.Post", "Post")
                        .WithMany("Vibes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_post_vibes_posts_post_id");

                    b.HasOne("Pulse.Core.Models.Entities.Vibe", "Vibe")
                        .WithMany("Posts")
                        .HasForeignKey("VibeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_vibes_vibes_vibe_id");

                    b.Navigation("Post");

                    b.Navigation("Vibe");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Special", b =>
                {
                    b.HasOne("Pulse.Core.Models.Entities.Venue", "Venue")
                        .WithMany("Specials")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_specials_venues_venue_id");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.TagSpecial", b =>
                {
                    b.HasOne("Pulse.Core.Models.Entities.Special", "Special")
                        .WithMany("Tags")
                        .HasForeignKey("SpecialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_specials_specials_special_id");

                    b.HasOne("Pulse.Core.Models.Entities.Tag", "Tag")
                        .WithMany("Specials")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tag_specials_tags_tag_id");

                    b.Navigation("Special");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Venue", b =>
                {
                    b.HasOne("Pulse.Core.Models.Entities.VenueType", "VenueType")
                        .WithMany("Venues")
                        .HasForeignKey("VenueTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_venues_venue_types_venue_type_id");

                    b.Navigation("VenueType");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Post", b =>
                {
                    b.Navigation("Vibes");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Special", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Tag", b =>
                {
                    b.Navigation("Specials");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Venue", b =>
                {
                    b.Navigation("BusinessHours");

                    b.Navigation("Posts");

                    b.Navigation("Specials");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.VenueType", b =>
                {
                    b.Navigation("Venues");
                });

            modelBuilder.Entity("Pulse.Core.Models.Entities.Vibe", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
