/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecialConfirmDeleteDialog: typeof import('./components/SpecialConfirmDeleteDialog.vue')['default']
    SpecialFormDialog: typeof import('./components/SpecialFormDialog.vue')['default']
    Specials: typeof import('./components/Specials.vue')['default']
    VenueActionBar: typeof import('./components/VenueActionBar.vue')['default']
    VenueConfirmDeleteDialog: typeof import('./components/VenueConfirmDeleteDialog.vue')['default']
    VenueDetailsCard: typeof import('./components/VenueDetailsCard.vue')['default']
    VenueFormDialog: typeof import('./components/VenueFormDialog.vue')['default']
    VenueSearchBar: typeof import('./components/VenueSearchBar.vue')['default']
    VenueSpecialForm: typeof import('./components/VenueSpecialForm.vue')['default']
    VenueSpecialsTable: typeof import('./components/VenueSpecialsTable.vue')['default']
    VenuesTable: typeof import('./components/VenuesTable.vue')['default']
  }
}
